### ISSUE TITLE
A message's `uid` is not rendered when a subscribe/publish block has a single message associated with it

### ISSUE THREAD

**Issue by stuartforrest-infinity** [asyncapi/markdown-template#141]
#### Describe the bug
When a channel's subscribe/publish block has a single message associated with it the `uid` is not being rendered. It doesn't look like this matches the behaviour of the `html-template` (see below). This behaviour is not ideal for our current use case but the motivation for this issue is what I think is an inconsistency between renderers. The rendering of `uid` is not necessarily the best property to output but the `title` property is also not output anywhere.

#### How to Reproduce
There is an explicit check to the parser [here](https://github.com/asyncapi/markdown-template/blob/master/components/Channels.js#L74) to check for multiple messages and the `uid` is not rendered if there is not multiple.

#### Expected behaviour
Having had a look at the html-template and the underlying react components (some of which the `markdown-template` replaces) I would expect the `uid` to be rendered whether there are single or multiple possible messages.

I'm happy to put together a PR if the expected behaviour is desirable.

**Comment by derberg** [comment]
@stuartforrest-infinity makes sense to me, feel free to open a PR. Please test your work against [this](https://github.com/asyncapi/generator/blob/master/test/docs/dummy.yml) file

**Comment by magicmatatjahu** [comment]
@stuartforrest-infinity PRs are more than welcome :)

**Comment by magicmatatjahu** [comment]
@stuartforrest-infinity Will you be looking to implement the described problem in the near future?

**Comment by stuartforrest-infinity** [comment]
@magicmatatjahu I can do that, yes. Other commitments have got a little on top of me but I'll put this in the calendar to take a look :)

**Comment by magicmatatjahu** [comment]
@stuartforrest-infinity Ok. From the issue's description, you know where to change the code, but if you will have problems, please ping me.

**Comment by stuartforrest-infinity** [comment]
@magicmatatjahu I'm not precious about it 😂 first one their wins!
