### ISSUE TITLE
Extra spaces in the HTML part of markdown

### ISSUE THREAD

**Issue by ximyro** [asyncapi/markdown-template#15]
#### Description
Hi!
I had generated documentation in markdown and I had tried to put it to the Confluence page.
The Confluence had not to show the page correctly because generated markdown has a lot of spaces in HTML markup.

Example

```markdown
 ##### Payload




<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th>Accepted values</th>
    </tr>
  </thead>
  <tbody>
    
      
<tr>
  <td>percentage </td>
  <td>integer</td>
  <td><p>Percentage to which the light should be dimmed to.</p>
</td>
  <td><em>Any</em></td>
</tr>







    
      
<tr>
  <td>sentAt </td>
  <td>string</td>
  <td><p>Date and time when the message was sent.</p>
</td>
  <td><em>Any</em></td>
</tr>


```

I had prepared the fix because I didn't have enough time to create an issue and pull request.
[Link](https://github.com/ximyro/markdown-template/tree/fix-extra-spaces) to branch with fixes.

Thank you for you project! After you approve this issue, I would like to create the pull request with fixes.

**Comment by derberg** [comment]
@ximyro Hi, awesome, thank for good words and contribution. Please open a pull request so it is easier to see what changes you introduced exactly. This is the best flow, rather then be jumping on your fork trying to figure out what you changed

**Comment by ximyro** [comment]
@derberg ok!

**Comment by ximyro** [comment]
Done https://github.com/asyncapi/markdown-template/pull/16
