### ISSUE TITLE
Add a custom Pull Request Template.

### ISSUE THREAD

**Issue by Ayush7614** [asyncapi/markdown-template#178]
#### Description

Create a custom Pull Request Template.

#### Additional Details

Make a Pull Request Template. Any new Contributor must be able to specify if he has met all the requirements like Clean Code, proper README and Documentation, Screenshots (If any) attached and more.

**Comment by Ayush7614** [comment]
Please assign me this issue under Hacktoberfest21

**Comment by derberg** [comment]
@Ayush7614 hey, we already have a PR template that is applied to all repos -> https://github.com/asyncapi/.github/blob/master/.github/pull_request_template.md

We do not maintain these per repo, unless necessary. 

I suggest you close this issue. If you want to help with some Markdown and Readme, we have lots of generator templates that do not have proper readme, including this Markdown template. All repos with `-template` suffix should follow structure of readme from [this](https://github.com/asyncapi/nodejs-template) repo (including [TOC autogeneration ](https://github.com/asyncapi/nodejs-template/blob/master/package.json#L25-L26)). Thoughts?

**Comment by magicmatatjahu** [comment]
Close this issue, @derberg described how you can help us in another repos. @Ayush7614 If you think that something should be added, please reopen issue or add comment :)
