### ISSUE TITLE
Switch for rendering whole channels by template parameter

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/markdown-template#194]
At the moment (from `0.19.0` version of template) we render channels as `Operations` - doesn't mean that we don't render the channel information as parameters etc. - we render it in the section of the given operation. However, some users may want to render a channel section (like before `0.19.0`) and we should make that available by template parameter.

Name of parameter should be discussed.

Action points:
- create and document additional parameter (name of parameter should be discussed) - more info about parameters https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file
- make condition to render channels or operations based on that new parameter in the https://github.com/asyncapi/markdown-template/blob/master/template/asyncapi.js file
- of course create new component to render channels :)
- add unit tests like in https://github.com/asyncapi/markdown-template/blob/master/test/components/Operations.test.js

This problem is involved in the [OpenForce event](https://github.com/asyncapi/website/pull/599). Please don't contribute if you are not participating in this event. If the problem is not solved at the end of the event, feel free to contribute :)

**Comment by alceil** [comment]
Hey @magicmatatjahu , I am Ashish Tom, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by magicmatatjahu** [comment]
@alceil Hi! Awesome! Please, you can work on it, if you will have any problems/question, please ping me in this thread :)

**Comment by alceil** [comment]
Thanks @magicmatatjahu

**Comment by derberg** [comment]
@alceil hey, all good? need a hand?

**Comment by alceil** [comment]
@magicmatatjahu @derberg I would like some pointers on how to get started. I'm a little confused tbh.

**Comment by magicmatatjahu** [comment]
@alceil first of all you should go through by this https://github.com/asyncapi/markdown-template#development section. Install needed deps and also install project deps. Then you should:

- create and document additional parameter (name of parameter should be discussed) in the Readme.md and also in the package.json - more info about parameters https://github.com/asyncapi/generator/blob/master/docs/authoring.md#configuration-file About name of that parameter: please suggest something. I prefer to have some 'renderingMode' or something like that but related to only channels/operations.
- make condition to render channels or operations based on that new parameter in the https://github.com/asyncapi/markdown-template/blob/master/template/asyncapi.js file
- of course create new component to render channels in the `components` dir - please try to reuse another existing components
- add unit tests like in https://github.com/asyncapi/markdown-template/blob/master/test/components/Operations.test.js

**Comment by alceil** [comment]
Ok got it @magicmatatjahu Thanks.

**Comment by Aaditya-Singh78** [comment]
Hi, I am Aaditya Singh, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by magicmatatjahu** [comment]
@Aaditya-Singh78 Go ahead :)

**Comment by derberg** [comment]
@Aaditya-Singh78 do you want to continue working on this one? I know OpenForce ended but if you are still interested and you were delayed by exams, we can still give you some time for this one
