### ISSUE TITLE
`1.0.0` release - discussion

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/markdown-template#195]
See @derberg 's comment -> https://github.com/asyncapi/markdown-template/pull/193#issuecomment-942283728

The template itself is stable and supports almost all things of AsyncAPI 2.0.0 (including 2.1.0 and 2.2.0) - the question is: Should we go with `1.0.0` version? As far as we know, a lot of people are using template in production and it's not causing too much trouble.

cc @derberg @fmvilas

**Comment by derberg** [comment]
the earth will not stand still if you release 1.0 and then in a month figure out 2.0 is needed, trust me 😄

**Comment by fmvilas** [comment]
> the earth will not stand still if you release 1.0 and then in a month figure out 2.0 is needed, trust me 😄

☝️ 😄
