### ISSUE TITLE
Add message name to output

### ISSUE THREAD

**Issue by schw4rzlicht** [asyncapi/markdown-template#22]
#### Reason/Context
~~OpenAPI~~ AsyncAPI allows messages to have a `name` property but it is not used in this generator template yet. I think it could improve readability.

#### Description
This would be a minor change and can simply be implemented changing the `operation.md` partial.

#### Pull Request
I already implemented this feature and would be happy to do a pull request when approved :)

**Comment by derberg** [comment]
Hey @schw4rzlicht I'm not sure where you want to display message name, especially that you mention OpenAPI. Do you have some example, screenshot?

**Comment by schw4rzlicht** [comment]
Hey @derberg Sorry, I meant AsyncAPI of course.

When generating the Markdown files, it generates headings for each message like `Message #42` instead of using the name of the message if it's set:

![Bildschirmfoto 2020-06-02 um 10 20 54](https://user-images.githubusercontent.com/19175262/83497458-ce493d00-a4ba-11ea-9a80-85299ad1dd2b.png)

**Comment by derberg** [comment]
oh, ok, so you want to use `message.uid()` to set a name.
I guess this is a case if you have multiple messages per channel.

How do you see it, just a name or `Message {name}`?

**Comment by schw4rzlicht** [comment]
> oh, ok, so you want to use `message.uid()` to set a name.

Actually I used `message.name()`. Both seem to work. What's the difference?

> I guess this is a case if you have multiple messages per channel.

Exactly. When using WebSocket for example.

> How do you see it, just a name or `Message {name}`?

Good question. Could also be `` Message `{name}` `` so we also have a better formatting. Might by my favourite, what do you think?

**Comment by derberg** [comment]
> Good question. Could also be Message `{name}` so we also have a better formatting. Might by my favourite, what do you think?

I'm also in favor of `Message ` as prefix I think

> Actually I used message.name(). Both seem to work. What's the difference?
the thing about the name is that it is not mandatory, and `uid()` is much more secure https://github.com/asyncapi/parser-js/blob/master/lib/models/message.js#L14
