### ISSUE TITLE
Adding parameter to change output file name

### ISSUE THREAD

**Issue by schw4rzlicht** [asyncapi/markdown-template#23]
#### Reason/Context
When generating output, the filename always is `asyncapi.md`. However this is not always viable.

#### Description
A template parameter could be added so that users can decide if the output file should be renamed. That parameter could default to `asyncapi.md` so this would be a minor change.

#### Pull Request
I already implemented this feature and would be happy to do a pull request when approved :)

**Comment by derberg** [comment]
Hi @schw4rzlicht  would be awesome to see what you have. Feel free to open PR if you have it done already.

**Comment by schw4rzlicht** [comment]
Yes, I used a hook for that feature.
