### ISSUE TITLE
Includes HTML tags which do not render in GIT readme

### ISSUE THREAD

**Issue by akshayaradhya** [asyncapi/markdown-template#33]
There are no options at the moment to generate the markdown without using HTML tags. The tables are generated in the following HTML format:

```
<table>
	<tr>
		<th>Month</th>
		<th>Savings</th>
		<th>Spending</th>
 	</tr>
 	<tr>
  		<td>January</td>
   		<td>$100</td>
		<td>$900</td>
 	</tr>
	<tr>
  		<td>July</td>
   		<td>$750</td>
		<td>$1000</td>
 	</tr>
	<tr>
  		<td>December</td>
   		<td>$250</td>
		<td>$300</td>
 	</tr>
	<tr>
  		<td>April</td>
   		<td>$400</td>
		<td>$700</td>
 	</tr>
</table>
```

instead of Markdown format:

```
|Month|Savings|Spending|
|--- |--- |--- |
|January|$100|$900|
|July|$750|$1000|
|December|$250|$300|
|April|$400|$700|
```

It also creates links using HTML <a> tag which is useless in Markdown because at the moment it does not really understand the references. 

Please give the option to generate markdowns without using these HTML tags that do not render on GIT.

Thanks!

**Comment by akshayaradhya** [comment]
> Hi @akshayaradhya can you please provide more details:
> 
> > instead of Markdown format
> > Markdown doesn't support tables, but inline HTML yes -> https://daringfireball.net/projects/markdown/syntax#html
> 
> > It also creates links using HTML tag
> > I checked, we have 3 such links and they are simple ones, easily can be changed into markdown links. Would like mind opening a PR for it?
> 
> > that do not render on GIT
> > Sorry, but what do you mean by GIT, where generated markdown doesn't render. I know some CMS apps can block HTML and prefer GFM support
> 
> GFM tables are not perfect, you cannot create such a table:
> 
> ```
> <table>
>   <thead>
>     <tr>
>       <th>URL</th>
>       <th>Protocol</th>
>       <th>Description</th>
>     </tr>
>   </thead>
>   <tbody>
>   <tr>
>       <td>mqtt://test.mosquitto.org:{port}</td>
>       <td>mqtt</td>
>       <td>Test broker</td>
>     </tr>
>     <tr>
>       <td colspan="3">
>         <details>
>           <summary>URL Variables</summary>
>           <table>
>             <thead>
>               <tr>
>                 <th>Name</th>
>                 <th>Default value</th>
>                 <th>Possible values</th>
>                 <th>Description</th>
>               </tr>
>             </thead>
>             <tbody>
>               <tr>
>                 <td>port</td>
>                 <td>
>                     1883
>                   </td>
>                 <td>
>                   <ul><li>1883</li><li>8883</li></ul>
>                   </td>
>                 <td>Secure connection (TLS) is available through port 8883.</td>
>               </tr>
>               </tbody>
>           </table>
>         </details>
>       </td>
>     </tr>
>     </tbody>
> </table>
> ```
> 
> How would you see this renders in GFM?

In GFM, this just shows tags as they are. And they are not even indented. And of course, no rendering. This is not at all useful in a markdown file. 

- Go to this link: https://playground.asyncapi.io/
- Copy the code from Markdown tab
- Commit that code into any of Bitbucket/Git repos
- Check if it renders everything.

Spoiler: It doesn't!!

Would be nice if you generated the "tables" in "markdown" format instead of HTML.

Also, please do not use <a> tags in the generated markdown. They do not work either in GFM.

Please let me know if you need more info

**Comment by derberg** [comment]
@akshayaradhya it looks good to me, https://github.com/derberg/test-experiment/blob/master/test.md

> Would be nice if you generated the "tables" in "markdown" format instead of HTML.

How would you see the table from above presented with GFM tables? this table is a complex table that is not possible to change into markdown 1:1

**Comment by akshayaradhya** [comment]
> @akshayaradhya it looks good to me, https://github.com/derberg/test-experiment/blob/master/test.md
>  I use Bitbucket and for me, these tables do not render at all. I just see tags.


> > Would be nice if you generated the "tables" in "markdown" format instead of HTML.
> 
> How would you see the table from above presented with GFM tables? this table is a complex table that is not possible to change into markdown 1:1
 At the moment, this is what I do:

- Generate my markdown using playground
- Copy the tables from markdown one by one and convert them from HTML to markdown using this link: https://jmalarcon.github.io/markdowntables/
- Replace each of the HTML tables to markdown
- Replace all the <a> tags with `## Header`
- Commit the code to Bitbucket

Only then it renders. Otherwise, it does not show renders but only tags. I am guessing bitbucket does not have support for inline HTML tags in markdown. But since such a conversion is possible, I am asking AsyncAPI to give this option to generate the documentation without using HTML tags!

I can also maybe talk to Bitbucket to provide support, but they are not as nice as you guys are ;)

**Comment by derberg** [comment]
@akshayaradhya I checked this table:

```html
<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Protocol</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
  <tr>
      <td>mqtt://test.mosquitto.org:{port}</td>
      <td>mqtt</td>
      <td>Test broker</td>
    </tr>
    <tr>
      <td colspan="3">
        <details>
          <summary>URL Variables</summary>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Default value</th>
                <th>Possible values</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>port</td>
                <td>
                    1883
                  </td>
                <td>
                  <ul><li>1883</li><li>8883</li></ul>
                  </td>
                <td>Secure connection (TLS) is available through port 8883.</td>
              </tr>
              </tbody>
          </table>
        </details>
      </td>
    </tr>
    </tbody>
</table>
```

with https://jmalarcon.github.io/markdowntables/
and got `ERROR: Your HTML table rows don't have the same number of cells. Colspan not supported.`

you probably do not have any server variables or security specified in your document, as this is where we use `colspan`. I guess that for Markdown version we could just put those variables and security information into a separate tables 🤔

**Comment by akshayaradhya** [comment]
> @akshayaradhya I checked this table:
> 
> ```
> <table>
>   <thead>
>     <tr>
>       <th>URL</th>
>       <th>Protocol</th>
>       <th>Description</th>
>     </tr>
>   </thead>
>   <tbody>
>   <tr>
>       <td>mqtt://test.mosquitto.org:{port}</td>
>       <td>mqtt</td>
>       <td>Test broker</td>
>     </tr>
>     <tr>
>       <td colspan="3">
>         <details>
>           <summary>URL Variables</summary>
>           <table>
>             <thead>
>               <tr>
>                 <th>Name</th>
>                 <th>Default value</th>
>                 <th>Possible values</th>
>                 <th>Description</th>
>               </tr>
>             </thead>
>             <tbody>
>               <tr>
>                 <td>port</td>
>                 <td>
>                     1883
>                   </td>
>                 <td>
>                   <ul><li>1883</li><li>8883</li></ul>
>                   </td>
>                 <td>Secure connection (TLS) is available through port 8883.</td>
>               </tr>
>               </tbody>
>           </table>
>         </details>
>       </td>
>     </tr>
>     </tbody>
> </table>
> ```
> 
> with https://jmalarcon.github.io/markdowntables/
> and got `ERROR: Your HTML table rows don't have the same number of cells. Colspan not supported.`
> 
> you probably do not have any server variables or security specified in your document, as this is where we use `colspan`. I guess that for Markdown version we could just put those variables and security information into a separate tables thinking

That's correct. I do not have server and security specification (at the moment), so all my tables do get converted in the above link without an issue. 

Do you think I should talk to bitbucket to extend support for inline HTML in markdowns? Or is there anything you can do from your end?

Thank you very much for the help so far! Really appreciate it!

**Comment by derberg** [comment]
@akshayaradhya you can try with Bitbucket but don't expect to much. If they do not support HTML in Markdown so far it means they have super-strong security team that made developers sanitize by default any HTML before it is rendered.

I say we should definitely support Markdown without HTML. Just the thing is what I wrote at the very beginning, `tables` are not part of Markdown spec, but an extra sugar added by the community. We could rework HTML tables to GitHub Flavoured Markdown syntax and maybe have a parameter like `-p gfm=true` (btw did you know you can generate your markdown with our CLI instead of doing it with the playground?) and then tables would be markdown style. 

Would be awesome if someone could jump in and help with it

**Comment by akshayaradhya** [comment]
> @akshayaradhya you can try with Bitbucket but don't expect to much. If they do not support HTML in Markdown so far it means they have super-strong security team that made developers sanitize by default any HTML before it is rendered.
> 
> I say we should definitely support Markdown without HTML. Just the thing is what I wrote at the very beginning, `tables` are not part of Markdown spec, but an extra sugar added by the community. We could rework HTML tables to GitHub Flavoured Markdown syntax and maybe have a parameter like `-p gfm=true` (btw did you know you can generate your markdown with our CLI instead of doing it with the playground?) and then tables would be markdown style.
>  Yes :) I generate mine with CLI using the command `ag asyncapi.yaml @asyncapi/markdown-template -o output`
However, this also includes HTML tags for tables


> Would be awesome if someone could jump in and help with it

**Comment by magicmatatjahu** [comment]
@akshayaradhya Hi! I already merged new version of `markdown-template` based on React not Nonjucks with native markdown tables, not html. Please, check your example with latest version `0.11.0` of template, and inform us about possible bugs :) You must also update `asyncapi-generator` (`ag`) to `1.1.0` version.

**Comment by derberg** [comment]
@akshayaradhya closing for now as there is no response from your side, but feel free to create another issue later if you find some issues in the new template
