### ISSUE TITLE
Render into multiple files

### ISSUE THREAD

**Issue by mrjingles** [asyncapi/markdown-template#342]
#### Reason/Context
We are using the markdown-template to render documents for Docusaurus from our AsyncAPI specs. Unfortunately the resulting file can get really huge in some cases what brings it to memory allocation issues. Splitting it into multiple files would solve the problem.

#### Description
My proposal would be to introduce another option to make the result be created with multiple files. One per operation and one for intro and table of contents. As it would be an additional parameter, it would be a non-breaking change.

**Comment by derberg** [comment]
Hey, that definitely makes sense. Would you be willing to contribute that feature?

**Comment by mrjingles** [comment]
Hey, I would be willing to do so, but I have no clue about javascript coding. =(

**Comment by derberg** [comment]
@mrjingles can you at least provide maybe a kind of example:
- asyncapi file
- current markdown
- expected markdown
?

@Arya-Gupta I wrote to you about contributing to CLI, but this is also a good option, since it is backend but the code/docs generation is actually based on a componentization concept from React, and we actually use React to render markdown files

**Comment by mrjingles** [comment]
Hey sure.. let me share some details. Attached you'll find an asyncapi.yaml and the converted asyncapi.md.

As you can see, the markdown file has about 30k+ lines. We use CloudEvents as well and the operations do not yet have payloads yet. So it will grow. =)

We export that file to a [Docusaurus](https://docusaurus.io) to have a proper visualization that integrates with our docu, as there is (afaik) no Docusaurus extension like for OpenAPI yet. That gets pretty slow. What I did was using [mdsplit](https://pypi.org/project/mdsplit/) to break the file. Works, but is really clumpy, using many sed commands.

I split like followed:

- the main part of the markdown file (everything except the operations)
- one file per operation
- created a new TOC (mdsplit)

A split like that keeps the file size manageable for us and I think in general.

Hope that helps. =)

[asyncapi.zip](https://github.com/asyncapi/markdown-template/files/11951087/asyncapi.zip)
