### ISSUE TITLE
message.messageId is not a function

### ISSUE THREAD

**Issue by remcocats** [asyncapi/markdown-template#385]
#### Describe the bug
When using the template with older version of the api contract I get the fault message.messageId is not a function.

when I look in de message.js I see the problem:
`// check typeof as fallback for older version than `2.4.0`
  const messageId = typeof message.messageId === 'function' && message.messageId();
  const headers = message.headers();
  const payload = message.payload();
  const correlationId = message.correlationId();
  const contentType = message.contentType();
  const externalDocs = message.externalDocs();
  const showInfoList = contentType || externalDocs;

  let header = 'Message';
  if (message.title()) {
    header += ` ${message.title()}`;
  }
  const id = message.messageId() || message.name() || message.id();
  if (id) {
    header += ` \`${id}\``;
  }`

When the const id is set the function message.messageId() is called this has to be messageId.

**Comment by abhikt48** [comment]
We are blocked by this issue.  I am hoping to fix this issue soon, so we can procedd further.

**Comment by SolomidHero** [comment]
i encountered same issue

**Comment by abhikt48** [comment]
@remcocats Do we know when PR can be approved?

**Comment by abhikt48** [comment]
Hey @jonaslagoni , Can you please suggest why I am getting this issue in Ubantatu system and not in alpine or windows system? It was working fine earlier and suddenly it's start to fail. We are really clueless for this issue. It will be great if you can give us some insight on this. We are blocked due to this issue.

**Comment by jonaslagoni** [comment]
@abhikt48 until https://github.com/asyncapi/markdown-template/pull/387 is fixed, there is not much you can do but downgrade 🙂
