### ISSUE TITLE
Generete reply information

### ISSUE THREAD

**Issue by CodeGlitcher** [asyncapi/markdown-template#452]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
De asyncapi 3.0 spec allows for message reply to be defined. Generated documentation should reflect this.
- How will this change help?
- What is the motivation? 
Other team members can easily see how this api works and what data they should expect.

When operation specifies a reply.
I expect that the generated markdown include this.
I think the generator should add a reply header with the detail of the reply.

#### Description
Please try answering few of those questions
- What changes have to be introduced?
- Will this be a breaking change?
Not sure

- How could it be implemented/designed?
I think a Replay block with details should keep thing readable.
### Reply
<details>
 Reply table / details
</details>

Added my test input and current output:
[current-output.md](https://github.com/asyncapi/markdown-template/files/14008987/current-output.md)
[input.yaml.txt](https://github.com/asyncapi/markdown-template/files/14008991/input.yaml.txt)

**Comment by korifey91** [comment]
I'm facing the same issue. In my spec file I have reply message and I need to see what message will be sent as a reply.

![image](https://github.com/asyncapi/markdown-template/assets/40362351/ac60690c-cc43-4cbe-891b-9a6a057bfdc8)

**Comment by derberg** [comment]
@CodeGlitcher please join review -> https://github.com/asyncapi/markdown-template/pull/523

**Comment by derberg** [comment]
solved with https://github.com/asyncapi/markdown-template/pull/523
