### ISSUE TITLE
Description after publish/subscribe in channel not in markdown

### ISSUE THREAD

**Issue by ryanskinner** [asyncapi/markdown-template#6]
#### Describe the bug
The `description` added to the `subscribe` or `publish` under the channel does not come out in the markdown (MD) document.

#### How to Reproduce
Use the following yml and export to MD. The playground.asyncapi.io can also be used.

```yml
asyncapi: '2.0.0'
defaultContentType: application/json
info:
  title: Example OneOf Issue
  version: '1.0.0'


components:
  messages:
    successMessage:
      name: Success
      payload:
          type: object
          properties:
            result:
              type: string
              examples:
                - success

    failureMessage:
      name: Failure
      payload:
          type: object
          properties:
            error:
              type: object
              properties:
                errorCode:
                  type: integer              
                errorMessage:
                  type: string
          examples:
            - 
              error:
                errorCode: 404
                errorMessage: Something messed up

channels:
  some.channel:
    subscribe:
      description: this doesn't show in markdown!
      message:
        oneOf:
          - $ref: '#/components/messages/successMessage'
          - $ref: '#/components/messages/failureMessage'
```
#### Expected behavior
The description should show in the MD document.

**Comment by derberg** [comment]
@ryanskinner Hey, thanks a lot. You are right, description is not rendered, summary I think as well. Could you provide a markdown where you suggest where those should be located? I could quickly add it so you see how it works and maybe you could contribute other missing parts if you have time

**Comment by ryanskinner** [comment]
@derberg Using the yml below, I propose the MD that's even further down.  I added both a summary and description.  Since MD doesn't give us much formatting to work with, I think the summary should be in italics.  The description, since it supports MD formatting directly, I think it should be below the summary and just rendered plainly (or with any MD formatting provided).

**YML file**
```yml
asyncapi: '2.0.0'
defaultContentType: application/json
info:
  title: Subscribe Summary and Description
  version: '1.0.0'

components:
  messages:
    successMessage:
      name: Success
      payload:
          type: object
          properties:
            result:
              type: string
              examples:
                - success

channels:
  some.channel:
    subscribe:
      summary: A summary of the channel
      description: |
        This is the description with **bold** text.
        
        One multiple lines.
      message:
        $ref: '#/components/messages/successMessage'
```

**Proposed MD output**
~~~markdown
# Subscribe Summary and Description 1.0.0 documentation

## Table of Contents

* [Channels](#channels)

## Channels

<a name="channel-some.channel"></a>

#### Channel Parameters

###  `subscribe` some.channel

*A summary of the channel*

This is the description with **bold** text.
        
One multiple lines.

#### Message

##### Payload

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Description</th>
      <th>Accepted values</th>
    </tr>
  </thead>
  <tbody>
      
<tr>
  <td>result </td>
  <td>string</td>
  <td></td>
  <td><em>Any</em></td>
</tr>
  </tbody>
</table>

###### Example of payload _(generated)_

```json
{
  "result": "success"
}
```

~~~

**Comment by derberg** [comment]
@ryanskinner thanks so much man, this makes implementation much easier on my side 🙇 
I'll just do it as you described it as at the end I do it for you now for me 😄

**Comment by derberg** [comment]
@ryanskinner it was even easier than I thought 😄 
Check out the PR. There is an instruction that you can use on your local to test my implementation with your file.

If you want to know how I did it, just look into `operation.md`  template, the rest of files is not related

**Comment by ryanskinner** [comment]
@derberg it looks good I tried it out with different variations and it seems to look good.

Thanks for the quick work.

**Comment by ryanskinner** [comment]
Just one little fix, please.  On my description text I accidentally wrote `One multiple lines` when it should be `On multiple lines`.    I noticed you added it to the test file.

**Comment by derberg** [comment]
@ryanskinner I hope you had a chance to have a look at how this feature was added. Please considering contributing new enhancement. Nunjucks syntax is described here https://mozilla.github.io/nunjucks/templating.html

We are at the moment super focused on hardening Generator and Parser in general, to deliver first major releases for them. Any help in enhancements for a specific template is appreciated.
