### ISSUE TITLE
Model representation on output file

### ISSUE THREAD

**Issue by mtzmontiel** [asyncapi/markdown-template#70]
#### Reason/Context

- Why we need this improvement?

Some projects use lots of Models and are referenced from Schemas independently of channels. Right now only messages are output as parameters on channels.
- How will this change help?

Right now there is no output of Models on markdown, it just gets skipped. Reutilization of definitions is hard if using this to document the API

- What is the motivation? 
SDK generators already use this so this should be part of feature completeness on markdown documentation

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Processing of Model section pretty similar to what schema is already doing but instead of adding within the parameters section perhaps as a top level and TOC entry for all Models included on source file.

- Will this be a breaking change?

Probably not a breaking change but an addition. Some refactors to de-duplicate might be needed
- How could it be implemented/designed?

Iterating over schema might be advisable

**Comment by derberg** [comment]
@mtzmontiel hey, just to make sure, you would like a separate, channels independent section that lists all schemas? just like in the html-template we list independently all messages? Would be awesome if you could present a sample output file that you see, you can base it on http://bit.ly/asyncapi

**Comment by derberg** [comment]
@mtzmontiel is this still valid for you?

**Comment by derberg** [comment]
no answers from requestor so closing
